### ISSUE TITLE
App wont start, getting these errors:

### ISSUE THREAD

**Issue by BurntAussieTyre** [DoubleYouC/Bethini-Pie-Performance-INI-Editor#13]
![fallout4inifail](https://github.com/DoubleYouC/Bethini-Pie-Performance-INI-Editor/assets/145847997/ed22f807-32c4-48ff-934c-8dacdeb84cd3)

**Comment by DoubleYouC** [comment]
Windows version?

**Comment by BurntAussieTyre** [comment]
Win 7 Pro x64 SP1.

**Comment by DoubleYouC** [comment]
OK. Sorry, but the binary is only compatible with Windows 10 and up.
