### ISSUE TITLE
No Ability to select game

### ISSUE THREAD

**Issue by WolfLord01** [DoubleYouC/Bethini-Pie-Performance-INI-Editor#14]
![Screenshot 2024-06-06 152105](https://github.com/DoubleYouC/Bethini-Pie-Performance-INI-Editor/assets/171982573/e241735d-0f5f-49b6-8024-94ff815131a6)

[log.log](https://github.com/user-attachments/files/15686560/log.log)

Hello Love this Program, but a couple of days ago I decided to fix some issues I was having in Starfield (BethBugs) Completely Uninstalled all mods, and the game itself (when I say completely, I mean used a powerful uninstaller Program after deleting thru steam to remove all registry edits, and the entire game folders (all of them)This is something I ALWAYS do when Uninstalling Programs). Then I reinstalled the Game (Starfield) to it's default Steam location, then using Vortex, installed all the Mods I know and Love (245 of 'em). then installed this Bethini the way you show in your video... (rewatched it to make certain I had it right)  but it comes up with the select game window but does not give me any options... it completely skips the path selection window ... it shows at the bottom : Tip; you can change the game at any time by going to File > Choose Game.... but there is nothing on the window I can click to get to File. and I have NO games in that window... it will not detect them installed on my computer even though they are all (Fallout 4, Skyrim SE And Starfield) installed to the default Steam Location. HELP PLEASE!!!!!!!!!

**Comment by DoubleYouC** [comment]
Please extract the entire archive. This should only happen if the "apps" folder in the Bethini Pie installation directory is empty.

**Comment by WolfLord01** [comment]
ok umm how do I do that?  I have already fully extracted the downloaded item.... where should I be Extracting it to? and the Apps folder is empty. like I said it is not registering the games already on the computer.   is there a way to manually put the apps into the apps folder so it sees them?

**Comment by WolfLord01** [comment]
WOW never mind I figured it out NOT your program.... the Zip software was not fully unzipping the file for some stupid reason....went to 7zip worked perfectly
