### ISSUE TITLE
Windows Defender reports Starfield BethINI PIE is Trojan Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by InsanityPrelude** [DoubleYouC/Bethini-Pie-Performance-INI-Editor#4]
![image](https://github.com/DoubleYouC/Bethini-Pie-Performance-INI-Editor/assets/38642020/626fdc65-7043-4462-b188-55deae681c49)

Downloaded version 4.1 from [here](https://www.nexusmods.com/site/mods/631?tab=files) and it was immediately quarantined by my system and I had to override it.  The "!ml" implies this is a "machine learning" based detection, so unless your entire toolchain is compromised somewhere it's 99% an overzealous false positive, just figured I'd generate a report on it in case there's something that can be done to remediate it.  Digitally signing it might let you get around this.

**Comment by DoubleYouC** [comment]
Submitted to Microsoft and the detection was removed in definition Security Intelligence Version 1.397.288.0.
