### ISSUE TITLE
Starfield values being saved to wrong ini file?

### ISSUE THREAD

**Issue by pelstob** [DoubleYouC/Bethini-Pie-Performance-INI-Editor#6]
It seems to be saving Starfield values in the wrong ini file, at least as far as [SaveGame] is concerned. I'm using an SFSE plug-in to turn quick-saves into auto-saves, so had increased iAutoSaveCount to 32 using Bethini. The updated limit wasn't working until I moved the values from StarfieldCustom.ini where Bethini placed them to starfield.ini.

**Comment by DoubleYouC** [comment]
Tested and verified the setting is working as intended in the vanilla game when used in the StarfieldCustom.ini. Any values valid in Starfield.ini are also valid in StarfieldCustom.ini. Values can be verified in-game using the console using getini "iAutoSaveCount:SaveGame" which returns the manually set value to be as set in StarfieldCustom.ini.
