### ISSUE TITLE
numerical input

### ISSUE THREAD

**Issue by selsie** [DoubleYouC/Bethini-Pie-Performance-INI-Editor#7]
I'm at "Ambient Occlusion" right now, and used the arrows to adjust the values. Suddenly the decimal point changed to a decimal comma (which is used in Germany) and the field is darkened.

This happens in all fields with a decimal point.

I guess this problem will only affect users in countries where a decimal comma is used.

**Comment by DoubleYouC** [comment]
Issue is caused by ttkbootstrap [here](https://github.com/israel-dryer/ttkbootstrap/blob/master/src/ttkbootstrap/dialogs/dialogs.py#L566). Will be fixed in 4.10.
